#!/bin/bash
function header() {
    clear
echo -e "$(tput setaf 2)
  ___  _       _____   ____  _           
 / _ \| |_ ___|___ /  |  _ \| |__   ___  
| (_) | __/ _ \ |_ \  | |_) | '_ \ / _ \ 
 \__, | ||  __/___) | |  _ <| |_) | (_) |
   /_/ \__\___|____/  |_| \_\_.__/ \___/ 
                                         $(tput sgr 0)\n\n\n"
}
function reqcheck() {
    echo "Checking requirements:"
if [[ `tshark -v 2>/dev/null` == *"Wireshark"* ]]
then
    echo -e "\n\033[42m\033[1mPASS:\033[0m tshark (wireshark-cli)\n"
else
    echo -e "\n\033[41m\033[1mFAIL:\033[0m Please install tshark (wireshark-cli)" && exit 1
fi
}

function scan () {
    sudo tshark -i ${1} -w /var/scanOutput.pcap > /dev/null 2>&1 &
    PID=$!
    for (( i=1; i<=$scantime; i++ ))
    do
    calc=$((i*100/$scantime))
   echo -ne "Loading ${calc}%\r"
   sleep 1
done
echo -ne 'Done scanning  \n'
kill -9 $PID 2> /dev/null && wait $PID 2> /dev/null
}

header
[ $# -ne 1 ] && echo -e "USAGE: `basename $0` [Interface Name]\n" && exit 1
[ `whoami` != "root" ] && echo -e "\033[91m! Run script again as root: sudo bash `basename $0` [Interface Name]\033[0m\n" && exit 1
broadcast=`ifconfig $1 | grep -w inet | awk '{print $6}'`
reqcheck
while true; do
echo -en "Enter scan timout (default 30s): "
read scantime
[ -z $scantime ] && scantime=30
scan $1
ipbeg=`echo "$broadcast"|cut -d '.' -f 1,2,3`
ips=` sudo tshark -r /var/scanOutput.pcap 2> /dev/null| grep ARP  |awk '{print $12}' `
ips=`sudo echo "$ips" | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b"`
ips=`for ip in $ips; do echo "$ip"|cut -d '.' -f 4;done`
for ip in ${ips}; do if [[ $ip =~ [0-9]* ]]; then array["$ip"]=`echo "$ips"| grep "$ip"| wc -l`;fi;done
for key in "${!array[@]}";do if [ ${array["$key"]} -gt 50 ];then found="$ipbeg.$key";fi;done
if [[ $found =~ "." ]]; then
echo -en "IP Found, Looking for MAC address  "
ping -c 5 "$found" > /dev/null
arp -an | grep "$found" | awk '{print $4}' > /var/mactemp &
while true
do
found2=`cat /var/mactemp | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}'`
[ -n $found2 ] && break
for X in '-' '\' '|' '/'
do
echo -en "\b$X"
sleep 0.1
done
done

echo -en "\r\033[KSuspected Device:\n [\033[93m!\033[0m] \033[91m$found\t\033[94m$found2\033[0m\n" && echo -e "\n\n\033[1;32m-Deleting temporary file\n-Exiting\n-Created by: Ayman Elya !\033[0m"  && sudo rm -f /var/scanOutput.pcap /var/mactemp && exit 0
else echo -e "No device detected\nTry again ? (y/n): "
read answer
[[ $answer == *"n"* || $answer == *"N"* ]] && echo -e "\n\n\033[1;32m-Deleting temporary file\n-Exiting\n-Created by: Ayman Elya !\033[0m" && sudo rm -f /var/scanOutput.pcap /var/mactemp && exit 0
fi
header
done
