#!/bin/bash
function header() {
    clear
echo -e "$(tput setaf 2)
  ___  _       _____   ____  _           
 / _ \| |_ ___|___ /  |  _ \| |__   ___  
| (_) | __/ _ \ |_ \  | |_) | '_ \ / _ \ 
 \__, | ||  __/___) | |  _ <| |_) | (_) |
   /_/ \__\___|____/  |_| \_\_.__/ \___/ 
                                         $(tput sgr 0)\n\n\n"
}
function reqcheck() {
    echo "Checking requirements:"
if [[ `tshark -v 2>/dev/null` == *"Wireshark"* ]]
then
    echo -e "\n$(tput setab 2)$(tput setaf 0)PASS:$(tput sgr 0) tshark (wireshark-cli)\n"
else
    echo -e "\n$(tput setab 1)$(tput setaf 0)FAIL:$(tput sgr 0) Please install tshark (wireshark-cli)" && exit 1
fi
}

function scan () {
    sudo tshark -w /tmp/scanOutput.pcap > /dev/null 2>&1 &
    PID=$!
    for (( i=1; i<=$scantime; i++ ))
do
calc=$((i*100/$scantime))
   echo -ne "Loading ${calc}%\r"
   sleep 1
done
echo -ne 'Done scanning  \n'
kill -9 $PID 2> /dev/null && wait $PID 2> /dev/null
}

function getips () {
while read -r i
do
if [ "$firstip" != "$i" ]
then
ping -c 2 $i > /dev/null
mac=`arp -a | grep $i | awk '{print $4}'`
echo -e "$(tput setaf 1)\t[!] $i\t==>\t$mac$(tput sgr 0)\n"
firstip=$i
fi
done <<< "$ips"
}
header
[ $# -ne 1 ] && echo -e "USAGE: `basename $0` [Interface Name]\n" && exit 1
[ `whoami` != "root" ] && echo -e "$(tput setaf 1)! Run script again as root: sudo bash `basename $0` [Interface Name]$(tput sgr 0)\n" && exit 1
broadcast=`ifconfig $1 | grep -w inet | awk '{print $6}'`
reqcheck

while true; do
echo -en "Enter scan timout (default 30s): "
read scantime
[ -z $scantime ] && scantime=30
scan
ips=`sudo tshark -r /tmp/scanOutput.pcap 2>/dev/null| grep ARP | grep $broadcast | awk '{print $12}'`
if [[ $ips == *"."* ]] 
then
echo -e "Suspected Device:\n"
getips
exit 0
else
echo -en "No device detected\nTry again ? (y/n): "
read answer
[[ $answer == *"n"* || $answer == *"N"* ]] && echo -e "$(tput setaf 2)-Deleting temporary file\n-Exiting\n-Created by: Ayman Elya !$(tput sgr 0)" && sudo rm -f /tmp/scanOutput.pcap && exit 0
fi
header
done
